# Site settings
title: Parks by the people
email: codeforchiba@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  公園を自分たちの手で変えよう！
baseurl: ""
url: "http://parksbythepeople.code4chiba.org"

# Build settings
markdown: kramdown
exclude:
  - "_asset"
  - ".bowerrc"
  - "bower.json"
  - "Gemfile"
  - "Gemfile.lock"
